run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
issues:
  exclude-rules:
    - linters:
        - staticcheck
      path: controllers/dspipeline_params.go
      text: SA1019  # exclude failures for deprecated warnings
linters-settings:
  revive:
    rules:
      - name: dot-imports
        severity: warning
        disabled: true
