apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-mariadb
resources:
  - deployment.yaml
  - pvc.yaml
  - secret.yaml
  - service.yaml
  - certs-secret.yaml
  - self-signed-ca-configmap.yaml
  - tls-config-configmap.yaml
