kind: ConfigMap
apiVersion: v1
metadata:
  name: tls-config
  namespace: test-mariadb
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
data:
  z-custom-my.cnf: |
    [mariadb]
    ssl_cert = /.mariadb/certs/public.crt
    ssl_key = /.mariadb/certs/private.key
    ssl_capath = /.mariadb/certs/CAs
    require_secure_transport = on
