apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub
resources:
- ../../base
patchesStrategicMerge:
- img_patch.yaml
images:
- name: controller
  newName: quay.io/mkumatag/data-science-pipelines-operator
  newTag: latest
