name: Build images from sources.
run-name: Build images from sources.
on:
  workflow_call:
    inputs:
      src_dspo_branch:
        type: string
        default: 'v1.0.x'
        description: 'Source branch to build DSPO from'
        required: true
      src_dsp_branch:
        type: string
        default: 'v1.0.x'
        description: 'Source branch to build DSP from'
        required: true
      target_tag:
        type: string
        default: 'vx.y.z'
        description: 'Target Image Tag'
        required: true
      quay_org:
        type: string
        default: 'opendatahub'
        description: 'Quay Organization'
        required: true
      dsp_org_repo:
        type: string
        default: 'opendatahub-io/data-science-pipelines'
        description: 'DSP org/repo'
        required: true
      overwrite_imgs:
        type: string
        default: 'true'
        description: 'Overwrite images in quay if they already exist for this release.'
        required: true
  workflow_dispatch:
    inputs:
      src_dspo_branch:
        type: string
        default: 'v1.0.x'
        description: 'Source branch to build DSPO from'
        required: true
      src_dsp_branch:
        type: string
        default: 'v1.0.x'
        description: 'Source branch to build DSP from'
        required: true
      target_tag:
        default: 'vx.y.z'
        description: 'Target Image Tag'
        required: true
      quay_org:
        default: 'opendatahub'
        description: 'Quay Organization'
        required: true
      dsp_org_repo:
        default: 'opendatahub-io/data-science-pipelines'
        description: 'DSP org/repo'
        required: true
      overwrite_imgs:
        type: string
        default: 'false'
        description: 'Overwrite images in quay if they already exist for this release.'
        required: true
env:
  IMAGE_REPO_DSPO: data-science-pipelines-operator
  IMAGE_REPO_SERVER: ds-pipelines-api-server
  IMAGE_REPO_UI: ds-pipelines-frontend
  IMAGE_REPO_PA: ds-pipelines-persistenceagent
  IMAGE_REPO_SWF: ds-pipelines-scheduledworkflow
  IMAGE_REPO_LAUNCHER: ds-pipelines-launcher
  IMAGE_REPO_DRIVER: ds-pipelines-driver
  SOURCE_DSPO_BRANCH: ${{ inputs.src_dspo_branch }}
  SOURCE_DSP_BRANCH: ${{ inputs.src_dsp_branch }}
  QUAY_ORG: ${{ inputs.quay_org }}
  QUAY_ID: ${{ secrets.QUAY_ID }}
  QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  TARGET_IMAGE_TAG: ${{ inputs.target_tag }}
  OVERWRITE_IMAGES: ${{ inputs.overwrite_imgs }}
jobs:
  DSPO-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSPO_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_DSPO }}
          DOCKERFILE: Dockerfile
          GH_REPO: ${{ github.repository }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  SERVER-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_SERVER }}
          DOCKERFILE: backend/Dockerfile
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  UI-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_UI }}
          DOCKERFILE: frontend/Dockerfile
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  PA-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_PA }}
          DOCKERFILE: backend/Dockerfile.persistenceagent
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  SWF-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_SWF }}
          DOCKERFILE: backend/Dockerfile.scheduledworkflow
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  DRIVER-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_DRIVER }}
          DOCKERFILE: backend/Dockerfile.driver
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}

  LAUNCHER-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        name: Build Image
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_DSP_BRANCH }}
        with:
          IMAGE_REPO: ${{ env.IMAGE_REPO_LAUNCHER }}
          DOCKERFILE: backend/Dockerfile.launcher
          GH_REPO: ${{ inputs.dsp_org_repo }}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}
